core/urls.py
from django.conf.urls import url


from .views import (home, carregarImg, simulador)
  
urlpatterns = [  
    url(r'^$', home, name='home'),
    url(r'^carregar-img/$', carregarImg, name='carregar-img'),
    url(r'^simulador/$', simulador, name='simulador'),
]   
    

pedras/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
]

core/models.py
from django.db import models


class ImageUser(models.Model):
    id_image = models.CharField(max_length=80)
    image = models.ImageField(
            upload_to="static/img/",
            null=True,
            blank=True,
            width_field="width_field",
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)

core/forms.py
from django import forms   

from .models import ImageUser 


class ImageUserForm(forms.ModelForm):
    class Meta:
        model = ImageUser
        fields = [              
            'image',  
        ]

core/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

import hashlib
import random
import string


from .forms import ImageUserForm
from .models import ImageUser

def home(request):
    
    context = {}
    return render(request, 'home.html', context)


def idImage():

    id_img = ""
    for i in range(10):
        id_img = id_img + random.choice(string.ascii_letters)
    id_img = hashlib.sha256(id_img.encode()).hexdigest()
    return id_img


def carregarImg(request):
    form = ImageUserForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.id_image = idImage()
        instance.save()        
        return redirect(reverse('core:simulador') + '?img=' + instance.id_image)  
        
    context = {              
        'form': form,
    }
    return render(request, 'forms.html', context)


def simulador(request):

    id_img = request.GET.get('img', False)
    query = ImageUser.objects.filter(id_image=id_img)
    q = query.values('image')[0]['image']
    user_img = q[q.find('/')+1 : ]

    context = {
        'user_img': user_img,
    }

    return render(request, 'simulador.html', context)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simulador</title>

    <link rel="icon" href="#"/>

<!--    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
-->
     <!-- Bootstrap Core CSS -->
     <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
 
     <!-- Custom CSS -->
     <link href="{% static 'css/custom.css' %}" rel="stylesheet">

</head>

<body onload="init();">

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'core:home' %}" class="navbar-brand">Loja</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'core:carregar-img' %}">Simulador</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#contato">Contato</a></li>
          </ul>

        </div>
      </div>
    </div>


    <div class="container container-table">         
        <div class="vertical-center-row">

        {% block content %}

        {% endblock %}

        </div>
    </div>

    <!-- scripts  -->
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.6.2/fabric.min.js"></script>

    <script src="{% static 'js/html2canvas.js' %}"></script>
     
    {% if user_img %}
        {% include 'javascript.html' %}
    {% endif %}

</body>

</html>

templates/forms.html
{% extends 'base.html'%}

{% block content %}
<div class="row row-centered">
    <div class="col-centered">
    <form action="" method='POST' id="post-form" enctype="multipart/form-data">
        {% csrf_token %}   
        {{ form.as_p }}    
         <input id="image" type='submit' value='Enviar'/>
    </form>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

templates/javascript.html
{% load staticfiles %}
<script> 

    function init() {
     
    canvas = new fabric.Canvas('parallax');

    //Imagem de fundo
    fabric.Image.fromURL("{% static user_img %}", function(img) {
        img.set({
            width: canvas.width, 
            height: canvas.height, 
            originX: 'left', 
            originY: 'top',
        });
        canvas.setBackgroundImage(img, canvas.renderAll.bind(canvas));
    });


    //Cria novos elementos e limita a área que eles aparecem a cada clique
    var cont_left = 50
    var cont_top = 50

    $("#btn1").click(function(event){
        event.preventDefault();
        console.log("Criou um novo objeto!!")
        fabric.Image.fromURL("{% static 'img/goose.png' %}", function(img) {
            img.set({
                left: cont_left, 
                top: cont_top,
                width: 50,
                height: 50,
            });

            canvas.add(img)

            if (cont_top >= 330) {
                if (cont_left >= 450){ 
                    cont_left = 50
                } else {
                    cont_left = cont_left + 5;
                }
                cont_top = 50;
            } else {
                cont_left += 5;
                cont_top += 20;
            }

        });
    })   


    //Apaga os objetos selecionados
    $("#btn2").click(function(event){
        event.preventDefault();

        if (canvas.getActiveObject() == null) { 
            canvas.getActiveGroup().forEachObject(function(o){ 
                canvas.remove(o);
            }); 
            canvas.discardActiveGroup().renderAll();
        } else {
            canvas.getActiveObject().remove();
        }
        console.log("Apagou objeto!!");

    })


    // Converte o conteudo do canvas para imagem e inicia o download

    var element = $("#html-content-holder"); // global variable
    var getCanvas = canvas; // global variable

    $("#btn-Convert-Html2Image").on('click', function () { 
        console.log("Download da tela!!");
        var imgageData = getCanvas.toDataURL("image/png");
        // Now browser starts downloading it instead of just showing it
        var newData = imgageData.replace(/^data:image\/png/, "data:application/octet-stream");
        $("#btn-Convert-Html2Image").attr("download", "simulador.png").attr("href", newData);
    });


    // Touch

    var info = document.getElementById('info');
                           
    canvas.on({            
        'touch:gesture': function() {
            var text = document.createTextNode(' Gesture ');
            info.insertBefore(text, info.firstChild);
        },
        'touch:drag': function() {
            var text = document.createTextNode(' Dragging ');
            info.insertBefore(text, info.firstChild);
        },
        'touch:orientation': function() {
            var text = document.createTextNode(' Orientation ');
            info.insertBefore(text, info.firstChild);
        },                 
        'touch:shake': function() {
            var text = document.createTextNode(' Shaking ');
            info.insertBefore(text, info.firstChild);
        },
        'touch:longpress': function() {
            var text = document.createTextNode(' Longpress ');
             info.insertBefore(text, info.firstChild);
        }
    }); 


    // Colisão nos limites do canvas

    canvas.observe('object:scaling', function (e) {
        var obj = e.target;
        if(obj.getHeight() > obj.canvas.height || obj.getWidth() > obj.canvas.width){
            obj.setScaleY(obj.originalState.scaleY);
            obj.setScaleX(obj.originalState.scaleX);        
        }
        obj.setCoords();
        if(obj.getBoundingRect().top - (obj.cornerSize / 2) < 0 || obj.getBoundingRect().left -  (obj.cornerSize / 2) < 0) {
            obj.top = Math.max(obj.top, obj.top-obj.getBoundingRect().top + (obj.cornerSize / 2));
            obj.left = Math.max(obj.left, obj.left-obj.getBoundingRect().left + (obj.cornerSize / 2));    
        }
        if(obj.getBoundingRect().top+obj.getBoundingRect().height + obj.cornerSize  > obj.canvas.height || obj.getBoundingRect().left+obj.getBoundingRect().width + obj.cornerSize  > obj.canvas.width) {
            obj.top = Math.min(obj.top, obj.canvas.height-obj.getBoundingRect().height+obj.top-obj.getBoundingRect().top - obj.cornerSize / 2);
            obj.left = Math.min(obj.left, obj.canvas.width-obj.getBoundingRect().width+obj.left-obj.getBoundingRect().left - obj.cornerSize /2);    
        }
    });

    canvas.observe('object:moving', function (e) {
        var obj = e.target;
        if(obj.getHeight() > obj.canvas.height || obj.getWidth() > obj.canvas.width){
            obj.setScaleY(obj.originalState.scaleY);
            obj.setScaleX(obj.originalState.scaleX);        
        }
        obj.setCoords();
        if(obj.getBoundingRect().top - (obj.cornerSize / 2) < 0 || obj.getBoundingRect().left -  (obj.cornerSize / 2) < 0) {
            obj.top = Math.max(obj.top, obj.top-obj.getBoundingRect().top + (obj.cornerSize / 2));
            obj.left = Math.max(obj.left, obj.left-obj.getBoundingRect().left + (obj.cornerSize / 2));    
        } 
        if(obj.getBoundingRect().top+obj.getBoundingRect().height + obj.cornerSize  > obj.canvas.height || obj.getBoundingRect().left+obj.getBoundingRect().width + obj.cornerSize  > obj.canvas.width) {
        obj.left = Math.min(obj.left, obj.canvas.width-obj.getBoundingRect().width+obj.left-obj.getBoundingRect().left - obj.cornerSize /2);    
        }
    });


}
</script>

templates/simulador.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="row row-centered">
        <div class="col-centered">
            <div class=col-md-2>
                <ul style="margin-top:50px;">
                    <li><a id="btn1" href="#">Pedra 1</a></li>
                    <li><a id="btn2" href="#">Apagar</a></li>
                    <li><a id="btn-Convert-Html2Image" href="#">Download</a></li>
                </ul>
            </div>
            <div class="col-md-8">
               <canvas id="parallax" width="640" height="480"
                        style="margin-top:50px; 
                        border:1px solid rgba(0,0,0,0.1);">
               </canvas>
            </div>
        </div>
    </div>
{% endblock %}